name: Improve a Profiler
description: Suggest a correction or improvement to an existing profiler
title: "[Fix]: "
labels: ["profiler"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the profiler
      placeholder:
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: Languages
      description: What languages can it profile?
      placeholder: e.g. Python, C/C++, OpenMP
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: E.g. an explanation of what is wrong or could be improved.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other relevant information about the profiler here.
      placeholder:
    validations:
      required: false
